services:
  ranger:
    build:
      context: .
      dockerfile: Dockerfile.ranger
      args:
        - RANGER_BASE_IMAGE=${RANGER_BASE_IMAGE}
        - RANGER_BASE_VERSION=${RANGER_BASE_VERSION}
        - RANGER_VERSION=${RANGER_VERSION}
        - RANGER_DB_TYPE=${RANGER_DB_TYPE}
        - KERBEROS_ENABLED=${KERBEROS_ENABLED}
    image: ranger:latest
    container_name: ranger
    hostname: ranger.rangernw
    volumes:
      - ./dist/keytabs/ranger:/etc/keytabs
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "6080:6080"
    depends_on:
      ranger-kdc:
        condition: service_started
      ranger-zk:
        condition: service_started
      ranger-db:
        condition: service_healthy
      ranger-solr:
        condition: service_started
    environment:
      - RANGER_VERSION
      - RANGER_DB_TYPE
      - KERBEROS_ENABLED
      - DEBUG_ADMIN=${DEBUG_ADMIN:-false}
    command:
      - /home/ranger/scripts/ranger.sh

  ranger-kdc:
    build:
      context: .
      dockerfile: Dockerfile.ranger-kdc
      args:
        - REALM=${KERBEROS_REALM}
        - KDC_HOST=${KERBEROS_KDC_HOST}
        - MASTER_PASSWORD=${KERBEROS_MASTER_PASSWORD}
        - ADMIN_PRINCIPAL=${KERBEROS_ADMIN_PRINCIPAL}
        - ADMIN_PASSWORD=${KERBEROS_ADMIN_PASSWORD}
    image: ranger-kdc:latest
    container_name: ranger-kdc
    hostname: ranger-kdc.rangernw
    volumes:
      - ./dist/keytabs:/etc/keytabs
    networks:
      - ranger
    ports:
      - "88:88"
      - "88:88/udp"
      - "749:749"

  ranger-db:
    extends:
      service: ${RANGER_DB_TYPE}
      file: docker-compose.ranger-db.yml

  ranger-zk:
    build:
      context: .
      dockerfile: Dockerfile.ranger-zk
      args:
        - ZK_VERSION=${ZK_VERSION}
        - KERBEROS_ENABLED=${KERBEROS_ENABLED}
    image: ranger-zk
    container_name: ranger-zk
    hostname: ranger-zk.rangernw
    networks:
      - ranger
    ports:
      - "2181:2181"
    environment:
      - KERBEROS_ENABLED

  ranger-solr:
    build:
      context: .
      dockerfile: Dockerfile.ranger-solr
      args:
        - SOLR_VERSION=${SOLR_VERSION}
        - KERBEROS_ENABLED=${KERBEROS_ENABLED}
    image: ranger-solr
    container_name: ranger-solr
    hostname: ranger-solr.rangernw
    volumes:
      - ./dist/keytabs/ranger-solr:/etc/keytabs
    networks:
      - ranger
    ports:
      - "8983:8983"
    depends_on:
      ranger-kdc:
        condition: service_started
      ranger-zk:
        condition: service_started
    environment:
      - KERBEROS_ENABLED
      - KRB5_CONFIG=/etc/krb5.conf
    command:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits/

networks:
  ranger:
    name: rangernw
