services:
  ranger-hbase:
    build:
      context: .
      dockerfile: Dockerfile.ranger-hbase
      args:
        - RANGER_BASE_IMAGE=${RANGER_BASE_IMAGE}
        - RANGER_BASE_VERSION=${RANGER_BASE_VERSION}
        - HBASE_VERSION=${HBASE_VERSION}
        - HBASE_PLUGIN_VERSION=${HBASE_PLUGIN_VERSION}
        - KERBEROS_ENABLED=${KERBEROS_ENABLED}
    image: ranger-hbase
    container_name: ranger-hbase
    hostname: ranger-hbase.rangernw
    volumes:
      - ./dist/keytabs/ranger-hbase:/etc/keytabs
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "16000:16000"
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
    depends_on:
      ranger-hadoop:
        condition: service_healthy
      ranger-zk:
        condition: service_started
    environment:
      - HBASE_VERSION
      - HBASE_PLUGIN_VERSION
      - KERBEROS_ENABLED

networks:
  ranger:
    name: rangernw
