services:
  ranger-hive:
    build:
      context: .
      dockerfile: Dockerfile.ranger-hive
      args:
        - RANGER_BASE_IMAGE=${RANGER_BASE_IMAGE}
        - RANGER_BASE_VERSION=${RANGER_BASE_VERSION}
        - HIVE_HADOOP_VERSION=${HIVE_HADOOP_VERSION}
        - HIVE_VERSION=${HIVE_VERSION}
        - HIVE_PLUGIN_VERSION=${HIVE_PLUGIN_VERSION}
        - TEZ_VERSION=${TEZ_VERSION}
        - RANGER_DB_TYPE=${RANGER_DB_TYPE}
        - KERBEROS_ENABLED=${KERBEROS_ENABLED}
    image: ranger-hive
    container_name: ranger-hive
    hostname: ranger-hive.rangernw
    volumes:
      - ./dist/keytabs/ranger-hive:/etc/keytabs
      - ./scripts/kdc/krb5.conf:/etc/krb5.conf:ro
      - ./dist/version:/home/ranger/dist/version:ro
      - ./scripts/hive/ranger-hive-plugin-install.properties:/opt/ranger/ranger-hive-plugin/install.properties
      - ./scripts/hive/hive-site-${RANGER_DB_TYPE}.xml:/home/ranger/scripts/hive-site.xml:ro
      - ./scripts/hadoop/core-site.xml:/home/ranger/scripts/core-site.xml:ro
      - ./scripts/hive/hive-log4j2.properties:/opt/hive/conf/hive-log4j2.properties
      - ./scripts/hive/hive-metastore-log4j2.properties:/opt/hive/conf/hive-metastore-log4j2.properties
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "10000:10000"
      - "9083:9083"
    depends_on:
      ranger:
        condition: service_started
      ranger-zk:
        condition: service_started
      ranger-hadoop:
        condition: service_healthy
    environment:
      - HIVE_HADOOP_VERSION
      - HIVE_VERSION
      - HIVE_PLUGIN_VERSION
      - TEZ_VERSION
      - RANGER_DB_TYPE
      - KERBEROS_ENABLED

networks:
  ranger:
    name: rangernw
