services:
  ranger-hadoop:
    build:
      context: .
      dockerfile: Dockerfile.ranger-hadoop
      args:
        - RANGER_BASE_IMAGE=${RANGER_BASE_IMAGE}
        - RANGER_BASE_VERSION=${RANGER_BASE_VERSION}
        - HADOOP_VERSION=${HADOOP_VERSION}
        - HDFS_PLUGIN_VERSION=${HDFS_PLUGIN_VERSION}
        - YARN_PLUGIN_VERSION=${YARN_PLUGIN_VERSION}
        - KERBEROS_ENABLED=${KERBEROS_ENABLED}
    image: ranger-hadoop
    container_name: ranger-hadoop
    hostname: ranger-hadoop.rangernw
    volumes:
      - ./dist/keytabs/ranger-hadoop:/etc/keytabs
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "9000:9000"
      - "8088:8088"
    depends_on:
      ranger:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "/home/ranger/scripts/ranger-hadoop-healthcheck.sh"]
      interval: 20s
      timeout: 10s
      retries: 40
      start_period: 40s
    environment:
      - HADOOP_VERSION
      - HDFS_PLUGIN_VERSION
      - YARN_PLUGIN_VERSION
      - KERBEROS_ENABLED

networks:
  ranger:
    name: rangernw
