services:
  ranger-audit:
    build:
      context: .
      dockerfile: Dockerfile.ranger-audit
      args:
        - RANGER_BASE_IMAGE=${RANGER_BASE_IMAGE}
        - RANGER_BASE_VERSION=${RANGER_BASE_VERSION}
        - RANGER_VERSION=${RANGER_VERSION}
        - KERBEROS_ENABLED=${KERBEROS_ENABLED}
    image: ranger-audit
    container_name: ranger-audit
    hostname: ranger-audit.rangernw
    stdin_open: true
    tty: true
    depends_on:
       ranger-kdc:
         condition: service_started
       ranger-kafka:
         condition: service_started
       ranger-solr:
         condition: service_started
       ranger-hadoop:
         condition: service_healthy
    ports:
      - "7081:7081"
      - "7182:7182"
    environment:
      JAVA_HOME: /opt/java/openjdk
      AUDIT_SERVER_HOME_DIR: /opt/ranger-audit
      AUDIT_SERVER_CONF_DIR: /opt/ranger-audit/conf
      AUDIT_SERVER_LOG_DIR: /opt/ranger-audit/logs
      AUDIT_SERVER_HEAP: "-Xms512m -Xmx2g"
      RANGER_VERSION: ${RANGER_VERSION}
      KERBEROS_ENABLED: ${KERBEROS_ENABLED}
    networks:
      - ranger
    volumes:
      - ./dist/keytabs/ranger-audit:/etc/keytabs
      - audit-logs:/opt/ranger-audit/logs
      - audit-spool:/var/log/audit-server/audit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  audit-logs:
  audit-spool:

networks:
  ranger:
    name: rangernw