services:
  ranger-tagsync:
    build:
      context: .
      dockerfile: Dockerfile.ranger-tagsync
      args:
        - RANGER_BASE_IMAGE=${RANGER_BASE_IMAGE}
        - RANGER_BASE_VERSION=${RANGER_BASE_VERSION}
        - TAGSYNC_VERSION=${TAGSYNC_VERSION}
        - KERBEROS_ENABLED=${KERBEROS_ENABLED}
    image: ranger-tagsync
    container_name: ranger-tagsync
    hostname: ranger-tagsync.rangernw
    volumes:
      - ./dist/keytabs/ranger-tagsync:/etc/keytabs
    stdin_open: true
    tty: true
    networks:
      - ranger
    depends_on:
      ranger:
        condition: service_started
    environment:
      - TAGSYNC_VERSION
      - DEBUG_TAGSYNC=${DEBUG_TAGSYNC:-false}
      - KERBEROS_ENABLED

networks:
  ranger:
    name: rangernw
