services:
  ranger-opensearch:
    build:
      context: .
      dockerfile: Dockerfile.ranger-opensearch
      args:
        - RANGER_BASE_IMAGE=${RANGER_BASE_IMAGE}
        - RANGER_BASE_VERSION=${RANGER_BASE_VERSION}
        - OPENSEARCH_VERSION=${OPENSEARCH_VERSION}
        - KERBEROS_ENABLED=${KERBEROS_ENABLED}
    image: ranger-opensearch
    container_name: ranger-opensearch
    hostname: ranger-opensearch.rangernw
    volumes:
      - ./dist/keytabs/ranger-opensearch:/etc/keytabs
      - opensearch-data:/opt/opensearch/data
      - opensearch-logs:/opt/opensearch/logs
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      ranger-kdc:
        condition: service_started
      ranger:
        condition: service_started
    environment:
      - OPENSEARCH_VERSION=${OPENSEARCH_VERSION}
      - KERBEROS_ENABLED=${KERBEROS_ENABLED}
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m

volumes:
  opensearch-data:
  opensearch-logs:

networks:
  ranger:
    name: rangernw

