services:
  ranger:
    build:
      context: .
      dockerfile: Dockerfile.ranger
      args:
        - RANGER_BASE_IMAGE=${RANGER_BASE_IMAGE}
        - RANGER_BASE_VERSION=${RANGER_BASE_VERSION}
        - RANGER_VERSION=${RANGER_VERSION}
        - RANGER_DB_TYPE=${RANGER_DB_TYPE}
    image: ranger:latest
    container_name: ranger
    hostname: ranger.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "6080:6080"
    depends_on:
      ranger-zk:
        condition: service_started
      ranger-db:
        condition: service_healthy
      ranger-solr:
        condition: service_started
    environment:
      - RANGER_VERSION
      - RANGER_DB_TYPE
      - DEBUG_ADMIN=${DEBUG_ADMIN:-false}
    command:
      - /home/ranger/scripts/ranger.sh

  ranger-db:
    extends:
      service: ${RANGER_DB_TYPE}
      file: docker-compose.ranger-db.yml

  ranger-zk:
    build:
      context: .
      dockerfile: Dockerfile.ranger-zk
      args:
        - ZK_VERSION=${ZK_VERSION}
    image: ranger-zk
    container_name: ranger-zk
    hostname: ranger-zk.example.com
    networks:
      - ranger
    ports:
      - "2181:2181"

  ranger-solr:
    build:
      context: .
      dockerfile: Dockerfile.ranger-solr
      args:
        - SOLR_VERSION=${SOLR_VERSION}
    image: ranger-solr
    container_name: ranger-solr
    hostname: ranger-solr.example.com
    networks:
      - ranger
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits/

networks:
  ranger:
    name: rangernw
