services:
  ranger-usersync:
    build:
      context: .
      dockerfile: Dockerfile.ranger-usersync
      args:
        - RANGER_BASE_IMAGE=${RANGER_BASE_IMAGE}
        - RANGER_BASE_VERSION=${RANGER_BASE_VERSION}
        - USERSYNC_VERSION=${USERSYNC_VERSION}
        - KERBEROS_ENABLED=${KERBEROS_ENABLED}
    image: ranger-usersync
    container_name: ranger-usersync
    hostname: ranger-usersync.rangernw
    volumes:
      - ./dist/keytabs/ranger-usersync:/etc/keytabs
    stdin_open: true
    tty: true
    networks:
      - ranger
    depends_on:
      ranger:
        condition: service_started
    environment:
      - USERSYNC_VERSION
      - ENABLE_FILE_SYNC_SOURCE
      - DEBUG_USERSYNC=${DEBUG_USERSYNC:-false}
      - KERBEROS_ENABLED

networks:
  ranger:
    name: rangernw
