services:
  ranger-kms:
    build:
      context: .
      dockerfile: Dockerfile.ranger-kms
      args:
        - RANGER_BASE_IMAGE=${RANGER_BASE_IMAGE}
        - RANGER_BASE_VERSION=${RANGER_BASE_VERSION}
        - KMS_VERSION=${KMS_VERSION}
        - RANGER_DB_TYPE=${RANGER_DB_TYPE}
    image: ranger-kms:latest
    container_name: ranger-kms
    hostname: ranger-kms.example.com
    stdin_open: true
    tty: true
    volumes:
      - ./config/ranger-kms:/opt/ranger/kms/ews/webapp/WEB-INF/classes/conf
    networks:
      - ranger
    ports:
      - "9292:9292"
    depends_on:
      ranger:
        condition: service_started
    environment:
      - KMS_VERSION
      - RANGER_DB_TYPE
      - KMS_IN_DOCKER=true
    command:
      - /home/ranger/scripts/ranger-kms.sh

networks:
  ranger:
    name: rangernw
