services:
  ranger-base:
    build:
      context: .
      dockerfile: Dockerfile.ranger-base
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - RANGER_BASE_JAVA_VERSION=${RANGER_BASE_JAVA_VERSION}
    image: ranger-base
    container_name: ranger-base
    networks:
      - ranger
    environment:
      - RANGER_VERSION

networks:
  ranger:
    name: rangernw
