services:
  ranger-kafka:
    build:
      context: .
      dockerfile: Dockerfile.ranger-kafka
      args:
        - RANGER_BASE_IMAGE=${RANGER_BASE_IMAGE}
        - RANGER_BASE_VERSION=${RANGER_BASE_VERSION}
        - KAFKA_VERSION=${KAFKA_VERSION}
        - KAFKA_PLUGIN_VERSION=${KAFKA_PLUGIN_VERSION}
        - KERBEROS_ENABLED=${KERBEROS_ENABLED}
    image: ranger-kafka
    container_name: ranger-kafka
    hostname: ranger-kafka.rangernw
    volumes:
      - ./dist/keytabs/ranger-kafka:/etc/keytabs
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "9092:9092"
    depends_on:
      ranger:
        condition: service_started
      ranger-zk:
        condition: service_started
    environment:
      - KAFKA_VERSION
      - KAFKA_PLUGIN_VERSION
      - KERBEROS_ENABLED

networks:
  ranger:
    name: rangernw
