services:
  ranger-knox:
    build:
      context: .
      dockerfile: Dockerfile.ranger-knox
      args:
        - RANGER_BASE_IMAGE=${RANGER_BASE_IMAGE}
        - RANGER_BASE_VERSION=${RANGER_BASE_VERSION}
        - KNOX_VERSION=${KNOX_VERSION}
        - KNOX_PLUGIN_VERSION=${KNOX_PLUGIN_VERSION}
        - KERBEROS_ENABLED=${KERBEROS_ENABLED}
    image: ranger-knox
    container_name: ranger-knox
    hostname: ranger-knox.rangernw
    volumes:
      - ./dist/keytabs/ranger-knox:/etc/keytabs
      - ./scripts/kdc/krb5.conf:/etc/krb5.conf:ro
      - ./scripts/hadoop/core-site.xml:/home/ranger/scripts/core-site.xml:ro
      - ./scripts/hadoop/hdfs-client-site.xml:/home/ranger/scripts/hdfs-site.xml:ro
      - ./dist/version:/home/ranger/dist/version:ro
      - ./scripts/knox/ranger-knox-sandbox.xml:/opt/knox/conf/topologies/sandbox.xml
      - ./scripts/knox/ranger-knox-plugin-install.properties:/opt/ranger/ranger-knox-plugin/install.properties
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "8443:8443"
    depends_on:
      ranger:
        condition: service_started
      ranger-zk:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "curl -k -i -u admin:admin-password 'https://localhost:8443/gateway/sandbox/webhdfs/v1/?op=LISTSTATUS'" ]
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 10s
    environment:
      - KNOX_VERSION
      - KNOX_PLUGIN_VERSION
      - KERBEROS_ENABLED

networks:
  ranger:
    name: rangernw
